cmake_minimum_required(VERSION 3.10)
project(StandaloneBase C)
include(CTest)
if(NOT WIN32)
  add_subdirectory(native/sbbase)
  add_subdirectory(native/sbwebserver)
endif()
option(BUILD_SBPROXY "Build the libcurl-based proxy" ON)
if(BUILD_SBPROXY AND NOT WIN32)
  add_subdirectory(native/sbproxy)
endif()
if(BUILD_TESTING)
  add_subdirectory(tests)
endif()
