package.path = arg[1] .. "/?.lua;" .. package.path
local state = require("ExtendedStorageState")
local function contents(path)
    local file = assert(io.open(path, "r"))
    local value = file:read("*a")
    file:close()
    return value
end
assert(not contents(arg[1] .. "/StandaloneBaseApplet.lua"):find("ubimkvol", 1, true))
assert(not contents(arg[1] .. "/StorageManager.lua"):find("ubimkvol", 1, true))
assert(state.statusLabel("ACTIVE") == "Active")
assert(state.statusLabel("AVAILABLE") == "Available")
assert(state.statusLabel("REBOOT_REQUIRED") == "Reboot required")
assert(state.statusLabel("unexpected") == "Error")
assert(state.stageText("COPYING_APPLETS") == "Copying applets...")
assert(state.stageText("CREATING_VOLUME"):find("Creating", 1, true))
assert(state.stageText("unknown") == nil)
assert(state.errorText(23):find("filesystem", 1, true))
assert(state.errorText(23, "physical_validation_safety_gate"):find("locked", 1, true))
assert(state.errorText("27"):find("Boot support", 1, true))
assert(state.errorText(28):find("factory storage layout", 1, true))
assert(state.errorText(29):find("enough", 1, true))
assert(state.errorText(30):find("creation tool", 1, true))
assert(state.errorText(31):find("could not be created", 1, true))
assert(state.errorText(32):find("left in place", 1, true))
assert(state.errorText(99):find("sbstorage.log", 1, true))
assert(state.mibFromKb(1024) == "1.0 MB")
print("extended-storage-state-tests-ok")
