#define _POSIX_C_SOURCE 200809L
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/ioctl.h>
#include <sys/utsname.h>
#include <unistd.h>

#define TARGET_BYTES (64ULL * 1024ULL * 1024ULL)
#define UBIFS_NODE_MAGIC 0x06101831U
#define UBIFS_SB_NODE 6
struct ubi_rsvol_req { int64_t bytes; int32_t vol_id; } __attribute__((packed));
#define UBI_IOC_MAGIC 'o'
#define UBI_IOCRSVOL _IOW(UBI_IOC_MAGIC, 2, struct ubi_rsvol_req)
typedef struct {
    char model[128], arch[64], kernel[128], firmware[128];
    char mountpoint[128], fs_type[32], volume[64], volume_type[32], volumes[512];
    long ubi_devices, total_pebs, avail_pebs, reserved_pebs, bad_pebs, flash_bytes;
    long leb_size, volume_lebs, corrupted, read_only;
    unsigned long long fs_total, fs_free;
    int ambiguous, mounted, unexpected_volumes;
} info_t;

static const char *root(void) { const char *p=getenv("SB_STORAGE_ROOT"); return p&&*p?p:""; }
static void path(char *out,size_t n,const char *p){snprintf(out,n,"%s%s",root(),p);}
static int read_text(const char *name,char *out,size_t n){char p[PATH_MAX];FILE*f;size_t z;path(p,sizeof p,name);f=fopen(p,"r");if(!f)return -1;z=fread(out,1,n-1,f);fclose(f);out[z]=0;while(z&&strchr("\r\n \t",out[z-1]))out[--z]=0;return 0;}
static long read_long(const char *name,long fallback){char b[64],*e;long v;if(read_text(name,b,sizeof b))return fallback;errno=0;v=strtol(b,&e,10);return errno||e==b?fallback:v;}
static int directory(const char *name){char p[PATH_MAX];struct stat s;path(p,sizeof p,name);return !stat(p,&s)&&S_ISDIR(s.st_mode);}
static long ubi_count(void){long n=0;char p[PATH_MAX];DIR*d;struct dirent*e;path(p,sizeof p,"/sys/class/ubi");d=opendir(p);if(!d)return 0;while((e=readdir(d))){int id;char tail;if(sscanf(e->d_name,"ubi%d%c",&id,&tail)==1){char q[PATH_MAX];snprintf(q,sizeof q,"/sys/class/ubi/%.255s",e->d_name);if(directory(q))n++;}}closedir(d);return n;}
static long flash_size(void){char p[PATH_MAX],line[256];FILE*f;unsigned long size;int id;path(p,sizeof p,"/proc/mtd");f=fopen(p,"r");if(!f)return -1;while(fgets(line,sizeof line,f))if(sscanf(line,"mtd%d: %lx",&id,&size)==2&&id==1){fclose(f);return (long)size;}fclose(f);return -1;}
static void cpu(info_t*i){char b[4096],*p,*e;if(read_text("/proc/cpuinfo",b,sizeof b))return;p=strstr(b,"Hardware");if(!p)return;p=strchr(p,':');if(!p)return;p++;while(*p==' '||*p=='\t')p++;e=strchr(p,'\n');if(e)*e=0;snprintf(i->model,sizeof i->model,"%s",p);}
static void mounts(info_t*i){char p[PATH_MAX],dev[128],mnt[128],type[32],line[512];FILE*f;path(p,sizeof p,"/proc/mounts");f=fopen(p,"r");if(!f)return;while(fgets(line,sizeof line,f)){if(sscanf(line,"%127s %127s %31s",dev,mnt,type)!=3)continue;if(!strcmp(type,"ubifs")&&!strcmp(mnt,"/mnt/storage")){snprintf(i->mountpoint,sizeof i->mountpoint,"%s",mnt);snprintf(i->fs_type,sizeof i->fs_type,"%s",type);if(!strncmp(dev,"ubi",3)){char*q=strchr(dev,':');if(q)snprintf(i->volume,sizeof i->volume,"%s",q+1);}i->mounted=1;}}fclose(f);}
static int expected_volume(const char*n){return !strcmp(n,"kernel")||!strcmp(n,"kernel_bak")||!strcmp(n,"cramfs")||!strcmp(n,"cramfs_bak")||!strcmp(n,"ubifs")||!strcmp(n,"ubifs_test");}
static void volume(info_t*i){char base[128]="/sys/class/ubi/ubi0",p[PATH_MAX],name[64],item[96];DIR*d;struct dirent*e;int matches=0;char full[PATH_MAX];path(full,sizeof full,base);d=opendir(full);if(!d)return;while((e=readdir(d))){int id;if(sscanf(e->d_name,"ubi0_%d",&id)!=1)continue;snprintf(p,sizeof p,"%s/%.255s/name",base,e->d_name);if(read_text(p,name,sizeof name))continue;snprintf(item,sizeof item,"%d:%.63s",id,name);if(i->volumes[0])strncat(i->volumes,",",sizeof i->volumes-strlen(i->volumes)-1);strncat(i->volumes,item,sizeof i->volumes-strlen(i->volumes)-1);if(!expected_volume(name))i->unexpected_volumes++;if(!strcmp(name,i->volume[0]?i->volume:"ubifs")){matches++;snprintf(p,sizeof p,"%s/%.255s/type",base,e->d_name);read_text(p,i->volume_type,sizeof i->volume_type);snprintf(p,sizeof p,"%s/%.255s/reserved_ebs",base,e->d_name);i->volume_lebs=read_long(p,-1);snprintf(p,sizeof p,"%s/%.255s/usable_eb_size",base,e->d_name);i->leb_size=read_long(p,-1);snprintf(p,sizeof p,"%s/%.255s/corrupted",base,e->d_name);i->corrupted=read_long(p,-1);}}closedir(d);i->ambiguous=matches!=1;}
static void filesystem(info_t*i){struct statvfs s;char p[PATH_MAX];if(*root()){i->fs_total=(unsigned long long)read_long("/sys/class/ubi/ubi0/test_fs_total_bytes",-1);i->fs_free=(unsigned long long)read_long("/sys/class/ubi/ubi0/test_fs_free_bytes",-1);return;}path(p,sizeof p,"/mnt/storage");if(!statvfs(p,&s)){i->fs_total=(unsigned long long)s.f_blocks*s.f_frsize;i->fs_free=(unsigned long long)s.f_bavail*s.f_frsize;}}
static void collect(info_t*i){struct utsname u;char b[256],*nl;memset(i,0,sizeof *i);i->ubi_devices=i->total_pebs=i->avail_pebs=i->reserved_pebs=i->bad_pebs=i->leb_size=i->volume_lebs=i->corrupted=i->read_only=i->flash_bytes=-1;cpu(i);if(!uname(&u)){snprintf(i->arch,sizeof i->arch,"%.63s",u.machine);snprintf(i->kernel,sizeof i->kernel,"%.127s",u.release);}if(!read_text("/proc/sys/kernel/architecture",b,sizeof b))snprintf(i->arch,sizeof i->arch,"%.63s",b);if(!read_text("/proc/sys/kernel/osrelease",b,sizeof b))snprintf(i->kernel,sizeof i->kernel,"%.127s",b);read_text("/etc/squeezeos.version",i->firmware,sizeof i->firmware);nl=strpbrk(i->firmware,"\r\n");if(nl)*nl=0;mounts(i);i->ubi_devices=ubi_count();i->flash_bytes=flash_size();i->total_pebs=read_long("/sys/class/ubi/ubi0/total_eraseblocks",-1);i->avail_pebs=read_long("/sys/class/ubi/ubi0/avail_eraseblocks",-1);i->reserved_pebs=read_long("/sys/class/ubi/ubi0/reserved_for_bad",-1);i->bad_pebs=read_long("/sys/class/ubi/ubi0/bad_peb_count",-1);i->read_only=read_long("/sys/class/ubi/ubi0/read_only",-1);volume(i);filesystem(i);}
static int compatible(const info_t*i,char*reason,size_t n){long target=i->leb_size>0?(long)((TARGET_BYTES+i->leb_size-1)/i->leb_size):-1;if(!strstr(i->model,"Baby")&&!strstr(i->model,"Squeezebox Radio")){snprintf(reason,n,"unsupported_model");return 0;}if(strncmp(i->arch,"arm",3)){snprintf(reason,n,"unsupported_architecture");return 0;}if(strncmp(i->kernel,"2.6.26",6)){snprintf(reason,n,"unsupported_kernel");return 0;}if(strcmp(i->firmware,"7.7.3 r16676")&&strcmp(i->firmware,"9.0.1 r17084")){snprintf(reason,n,"unsupported_firmware");return 0;}if(i->ubi_devices!=1){snprintf(reason,n,"unexpected_ubi_device_count");return 0;}if(i->unexpected_volumes||!strstr(i->volumes,"kernel_bak")||!strstr(i->volumes,"cramfs_bak")||!strstr(i->volumes,"ubifs")){snprintf(reason,n,"unexpected_volume_layout");return 0;}if(!i->mounted||strcmp(i->fs_type,"ubifs")||strcmp(i->volume,"ubifs")){snprintf(reason,n,"writable_mount_not_verified");return 0;}if(i->ambiguous){snprintf(reason,n,"ambiguous_volume");return 0;}if(strcmp(i->volume_type,"dynamic")){snprintf(reason,n,"volume_not_dynamic");return 0;}if(i->corrupted!=0){snprintf(reason,n,"volume_corrupted_or_unknown");return 0;}if(i->read_only==1){snprintf(reason,n,"ubi_read_only");return 0;}if(target<0||i->volume_lebs<0||i->avail_pebs<target-i->volume_lebs){snprintf(reason,n,"insufficient_capacity");return 0;}snprintf(reason,n,"supported_read_only");return 1;}
static void output(const info_t*i){char reason[96];long target=i->leb_size>0?(long)((TARGET_BYTES+i->leb_size-1)/i->leb_size):-1;int ok=compatible(i,reason,sizeof reason);printf("schema=1\nmodel=%s\narchitecture=%s\nkernel=%s\nfirmware=%s\n",i->model,i->arch,i->kernel,i->firmware);printf("mountpoint=%s\nfilesystem=%s\nvolume=%s\nvolume_type=%s\nvolumes=%s\n",i->mountpoint,i->fs_type,i->volume,i->volume_type,i->volumes);printf("flash_bytes=%ld\nubi_devices=%ld\ntotal_pebs=%ld\navailable_pebs=%ld\nreserved_pebs=%ld\nbad_pebs=%ld\nleb_size=%ld\nvolume_lebs=%ld\n",i->flash_bytes,i->ubi_devices,i->total_pebs,i->avail_pebs,i->reserved_pebs,i->bad_pebs,i->leb_size,i->volume_lebs);printf("filesystem_total_bytes=%llu\nfilesystem_free_bytes=%llu\ntarget_bytes=%llu\ntarget_lebs=%ld\ncompatible=%s\nreason=%s\nexpansion_enabled=false\n",i->fs_total,i->fs_free,TARGET_BYTES,target,ok?"true":"false",reason);}
static uint32_t le32(const unsigned char*p){return (uint32_t)p[0]|(uint32_t)p[1]<<8|(uint32_t)p[2]<<16|(uint32_t)p[3]<<24;}
static uint64_t le64(const unsigned char*p){return (uint64_t)le32(p)|(uint64_t)le32(p+4)<<32;}
static int inspect_superblock(const char*name){unsigned char b[128];int fd=open(name,O_RDONLY);ssize_t n;if(fd<0){perror(name);return 66;}n=read(fd,b,sizeof b);close(fd);if(n<(ssize_t)sizeof b){fprintf(stderr,"short UBIFS superblock read\n");return 65;}printf("schema=1\nkind=ubifs_superblock\nmagic=0x%08x\n",le32(b));if(le32(b)!=UBIFS_NODE_MAGIC||b[20]!=UBIFS_SB_NODE){printf("valid=false\nreason=not_ubifs_superblock\n");return 2;}printf("valid=true\nnode_length=%u\nsequence=%llu\nflags=%u\nmin_io_size=%u\nleb_size=%u\nleb_cnt=%u\nmax_leb_cnt=%u\nmax_bud_bytes=%llu\nlog_lebs=%u\nlpt_lebs=%u\norph_lebs=%u\njhead_cnt=%u\nfanout=%u\nlsave_cnt=%u\nformat_version=%u\nread_version=0\nformat=w%u/r0\ndefault_compressor=%u\n",le32(b+16),(unsigned long long)le64(b+8),le32(b+28),le32(b+32),le32(b+36),le32(b+40),le32(b+44),(unsigned long long)le64(b+48),le32(b+56),le32(b+60),le32(b+64),le32(b+68),le32(b+72),le32(b+76),le32(b+80),le32(b+80),b[84]|(unsigned)b[85]<<8);return 0;}
static int test_volume_id(void){char base[128]="/sys/class/ubi/ubi0",p[PATH_MAX],name[64],type[32],full[PATH_MAX];DIR*d;struct dirent*e;int found=-1;path(full,sizeof full,base);d=opendir(full);if(!d)return -1;while((e=readdir(d))){int id;if(sscanf(e->d_name,"ubi0_%d",&id)!=1)continue;snprintf(p,sizeof p,"%s/%.255s/name",base,e->d_name);if(read_text(p,name,sizeof name)||strcmp(name,"ubifs_test"))continue;snprintf(p,sizeof p,"%s/%.255s/type",base,e->d_name);if(read_text(p,type,sizeof type)||strcmp(type,"dynamic")){found=-2;break;}snprintf(p,sizeof p,"%s/%.255s/corrupted",base,e->d_name);if(read_long(p,-1)!=0){found=-2;break;}if(found>=0){found=-2;break;}found=id;}closedir(d);return found;}
static int test_volume_mounted(void){char p[PATH_MAX],line[512];FILE*f;path(p,sizeof p,"/proc/mounts");f=fopen(p,"r");if(!f)return 1;while(fgets(line,sizeof line,f))if(strstr(line,"ubi0:ubifs_test ")||strstr(line," ubifs_test ")){fclose(f);return 1;}fclose(f);return 0;}
static int resize_test_volume(const char*size_text,const char*confirmation){char*end;long long bytes;int id,fd;struct ubi_rsvol_req req;if(strcmp(confirmation,"I_ACCEPT_TEST_VOLUME_FLASH_WRITE")){fprintf(stderr,"confirmation token rejected\n");return 77;}if(*root()){fprintf(stderr,"resize disabled with SB_STORAGE_ROOT\n");return 78;}errno=0;bytes=strtoll(size_text,&end,10);if(errno||*end||bytes<4*1024*1024LL||bytes>64*1024*1024LL){fprintf(stderr,"invalid test volume size\n");return 64;}id=test_volume_id();if(id<0){fprintf(stderr,"ubifs_test identity/type/corruption check failed\n");return 78;}if(test_volume_mounted()){fprintf(stderr,"ubifs_test is mounted or mount state is unknown\n");return 78;}fd=open("/dev/ubi0",O_RDONLY);if(fd<0){perror("/dev/ubi0");return 74;}req.bytes=bytes;req.vol_id=id;if(ioctl(fd,UBI_IOCRSVOL,&req)){perror("UBI_IOCRSVOL");close(fd);return 74;}close(fd);printf("resized_volume=ubifs_test\nvolume_id=%d\nrequested_bytes=%lld\n",id,bytes);return 0;}
int main(int argc,char**argv){info_t i;if(argc==3&&!strcmp(argv[1],"inspect-superblock"))return inspect_superblock(argv[2]);if(argc==4&&!strcmp(argv[1],"resize-test-volume"))return resize_test_volume(argv[2],argv[3]);if(argc!=2){fprintf(stderr,"usage: sb-storage-helper info|check|inspect-superblock FILE|resize-test-volume BYTES TOKEN|expand\n");return 64;}if(!strcmp(argv[1],"expand")){fprintf(stderr,"production expansion is intentionally disabled\n");return 78;}if(strcmp(argv[1],"info")&&strcmp(argv[1],"check")){fprintf(stderr,"unknown command\n");return 64;}collect(&i);output(&i);return !strcmp(argv[1],"check")&&!compatible(&i,(char[96]){0},96)?2:0;}
