#define _POSIX_C_SOURCE 200809L
#include <dirent.h>
#include <errno.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/utsname.h>

#define TARGET_BYTES (64ULL * 1024ULL * 1024ULL)
typedef struct {
    char model[128], arch[64], kernel[128], firmware[128];
    char mountpoint[128], fs_type[32], volume[64], volume_type[32], volumes[512];
    long ubi_devices, total_pebs, avail_pebs, reserved_pebs, bad_pebs, flash_bytes;
    long leb_size, volume_lebs, corrupted, read_only;
    unsigned long long fs_total, fs_free;
    int ambiguous, mounted, unexpected_volumes;
} info_t;

static const char *root(void) { const char *p=getenv("SB_STORAGE_ROOT"); return p&&*p?p:""; }
static void path(char *out,size_t n,const char *p){snprintf(out,n,"%s%s",root(),p);}
static int read_text(const char *name,char *out,size_t n){char p[PATH_MAX];FILE*f;size_t z;path(p,sizeof p,name);f=fopen(p,"r");if(!f)return -1;z=fread(out,1,n-1,f);fclose(f);out[z]=0;while(z&&strchr("\r\n \t",out[z-1]))out[--z]=0;return 0;}
static long read_long(const char *name,long fallback){char b[64],*e;long v;if(read_text(name,b,sizeof b))return fallback;errno=0;v=strtol(b,&e,10);return errno||e==b?fallback:v;}
static int directory(const char *name){char p[PATH_MAX];struct stat s;path(p,sizeof p,name);return !stat(p,&s)&&S_ISDIR(s.st_mode);}
static long ubi_count(void){long n=0;char p[PATH_MAX];DIR*d;struct dirent*e;path(p,sizeof p,"/sys/class/ubi");d=opendir(p);if(!d)return 0;while((e=readdir(d))){int id;char tail;if(sscanf(e->d_name,"ubi%d%c",&id,&tail)==1){char q[PATH_MAX];snprintf(q,sizeof q,"/sys/class/ubi/%.255s",e->d_name);if(directory(q))n++;}}closedir(d);return n;}
static long flash_size(void){char p[PATH_MAX],line[256];FILE*f;unsigned long size;int id;path(p,sizeof p,"/proc/mtd");f=fopen(p,"r");if(!f)return -1;while(fgets(line,sizeof line,f))if(sscanf(line,"mtd%d: %lx",&id,&size)==2&&id==1){fclose(f);return (long)size;}fclose(f);return -1;}
static void cpu(info_t*i){char b[4096],*p,*e;if(read_text("/proc/cpuinfo",b,sizeof b))return;p=strstr(b,"Hardware");if(!p)return;p=strchr(p,':');if(!p)return;p++;while(*p==' '||*p=='\t')p++;e=strchr(p,'\n');if(e)*e=0;snprintf(i->model,sizeof i->model,"%s",p);}
static void mounts(info_t*i){char p[PATH_MAX],dev[128],mnt[128],type[32],line[512];FILE*f;path(p,sizeof p,"/proc/mounts");f=fopen(p,"r");if(!f)return;while(fgets(line,sizeof line,f)){if(sscanf(line,"%127s %127s %31s",dev,mnt,type)!=3)continue;if(!strcmp(type,"ubifs")&&!strcmp(mnt,"/mnt/storage")){snprintf(i->mountpoint,sizeof i->mountpoint,"%s",mnt);snprintf(i->fs_type,sizeof i->fs_type,"%s",type);if(!strncmp(dev,"ubi",3)){char*q=strchr(dev,':');if(q)snprintf(i->volume,sizeof i->volume,"%s",q+1);}i->mounted=1;}}fclose(f);}
static int expected_volume(const char*n){return !strcmp(n,"kernel")||!strcmp(n,"kernel_bak")||!strcmp(n,"cramfs")||!strcmp(n,"cramfs_bak")||!strcmp(n,"ubifs")||!strcmp(n,"ubifs_test");}
static void volume(info_t*i){char base[128]="/sys/class/ubi/ubi0",p[PATH_MAX],name[64];DIR*d;struct dirent*e;int matches=0;char full[PATH_MAX];path(full,sizeof full,base);d=opendir(full);if(!d)return;while((e=readdir(d))){int id;if(sscanf(e->d_name,"ubi0_%d",&id)!=1)continue;snprintf(p,sizeof p,"%s/%.255s/name",base,e->d_name);if(read_text(p,name,sizeof name))continue;if(i->volumes[0])strncat(i->volumes,",",sizeof i->volumes-strlen(i->volumes)-1);strncat(i->volumes,name,sizeof i->volumes-strlen(i->volumes)-1);if(!expected_volume(name))i->unexpected_volumes++;if(!strcmp(name,i->volume[0]?i->volume:"ubifs")){matches++;snprintf(p,sizeof p,"%s/%.255s/type",base,e->d_name);read_text(p,i->volume_type,sizeof i->volume_type);snprintf(p,sizeof p,"%s/%.255s/reserved_ebs",base,e->d_name);i->volume_lebs=read_long(p,-1);snprintf(p,sizeof p,"%s/%.255s/usable_eb_size",base,e->d_name);i->leb_size=read_long(p,-1);snprintf(p,sizeof p,"%s/%.255s/corrupted",base,e->d_name);i->corrupted=read_long(p,-1);}}closedir(d);i->ambiguous=matches!=1;}
static void filesystem(info_t*i){struct statvfs s;char p[PATH_MAX];if(*root()){i->fs_total=(unsigned long long)read_long("/sys/class/ubi/ubi0/test_fs_total_bytes",-1);i->fs_free=(unsigned long long)read_long("/sys/class/ubi/ubi0/test_fs_free_bytes",-1);return;}path(p,sizeof p,"/mnt/storage");if(!statvfs(p,&s)){i->fs_total=(unsigned long long)s.f_blocks*s.f_frsize;i->fs_free=(unsigned long long)s.f_bavail*s.f_frsize;}}
static void collect(info_t*i){struct utsname u;char b[256],*nl;memset(i,0,sizeof *i);i->ubi_devices=i->total_pebs=i->avail_pebs=i->reserved_pebs=i->bad_pebs=i->leb_size=i->volume_lebs=i->corrupted=i->read_only=i->flash_bytes=-1;cpu(i);if(!uname(&u)){snprintf(i->arch,sizeof i->arch,"%.63s",u.machine);snprintf(i->kernel,sizeof i->kernel,"%.127s",u.release);}if(!read_text("/proc/sys/kernel/architecture",b,sizeof b))snprintf(i->arch,sizeof i->arch,"%.63s",b);if(!read_text("/proc/sys/kernel/osrelease",b,sizeof b))snprintf(i->kernel,sizeof i->kernel,"%.127s",b);read_text("/etc/squeezeos.version",i->firmware,sizeof i->firmware);nl=strpbrk(i->firmware,"\r\n");if(nl)*nl=0;mounts(i);i->ubi_devices=ubi_count();i->flash_bytes=flash_size();i->total_pebs=read_long("/sys/class/ubi/ubi0/total_eraseblocks",-1);i->avail_pebs=read_long("/sys/class/ubi/ubi0/avail_eraseblocks",-1);i->reserved_pebs=read_long("/sys/class/ubi/ubi0/reserved_for_bad",-1);i->bad_pebs=read_long("/sys/class/ubi/ubi0/bad_peb_count",-1);i->read_only=read_long("/sys/class/ubi/ubi0/read_only",-1);volume(i);filesystem(i);}
static int compatible(const info_t*i,char*reason,size_t n){long target=i->leb_size>0?(long)((TARGET_BYTES+i->leb_size-1)/i->leb_size):-1;if(!strstr(i->model,"Baby")&&!strstr(i->model,"Squeezebox Radio")){snprintf(reason,n,"unsupported_model");return 0;}if(strncmp(i->arch,"arm",3)){snprintf(reason,n,"unsupported_architecture");return 0;}if(strncmp(i->kernel,"2.6.26",6)){snprintf(reason,n,"unsupported_kernel");return 0;}if(strncmp(i->firmware,"7.7.3 r16676",12)){snprintf(reason,n,"unsupported_firmware");return 0;}if(i->ubi_devices!=1){snprintf(reason,n,"unexpected_ubi_device_count");return 0;}if(i->unexpected_volumes||!strstr(i->volumes,"kernel_bak")||!strstr(i->volumes,"cramfs_bak")||!strstr(i->volumes,"ubifs")){snprintf(reason,n,"unexpected_volume_layout");return 0;}if(!i->mounted||strcmp(i->fs_type,"ubifs")||strcmp(i->volume,"ubifs")){snprintf(reason,n,"writable_mount_not_verified");return 0;}if(i->ambiguous){snprintf(reason,n,"ambiguous_volume");return 0;}if(strcmp(i->volume_type,"dynamic")){snprintf(reason,n,"volume_not_dynamic");return 0;}if(i->corrupted!=0){snprintf(reason,n,"volume_corrupted_or_unknown");return 0;}if(i->read_only==1){snprintf(reason,n,"ubi_read_only");return 0;}if(target<0||i->volume_lebs<0||i->avail_pebs<target-i->volume_lebs){snprintf(reason,n,"insufficient_capacity");return 0;}snprintf(reason,n,"supported_read_only");return 1;}
static void output(const info_t*i){char reason[96];long target=i->leb_size>0?(long)((TARGET_BYTES+i->leb_size-1)/i->leb_size):-1;int ok=compatible(i,reason,sizeof reason);printf("schema=1\nmodel=%s\narchitecture=%s\nkernel=%s\nfirmware=%s\n",i->model,i->arch,i->kernel,i->firmware);printf("mountpoint=%s\nfilesystem=%s\nvolume=%s\nvolume_type=%s\nvolumes=%s\n",i->mountpoint,i->fs_type,i->volume,i->volume_type,i->volumes);printf("flash_bytes=%ld\nubi_devices=%ld\ntotal_pebs=%ld\navailable_pebs=%ld\nreserved_pebs=%ld\nbad_pebs=%ld\nleb_size=%ld\nvolume_lebs=%ld\n",i->flash_bytes,i->ubi_devices,i->total_pebs,i->avail_pebs,i->reserved_pebs,i->bad_pebs,i->leb_size,i->volume_lebs);printf("filesystem_total_bytes=%llu\nfilesystem_free_bytes=%llu\ntarget_bytes=%llu\ntarget_lebs=%ld\ncompatible=%s\nreason=%s\nexpansion_enabled=false\n",i->fs_total,i->fs_free,TARGET_BYTES,target,ok?"true":"false",reason);}
int main(int argc,char**argv){info_t i;if(argc!=2){fprintf(stderr,"usage: sb-storage-helper info|check|expand\n");return 64;}if(!strcmp(argv[1],"expand")){fprintf(stderr,"expansion is intentionally disabled\n");return 78;}if(strcmp(argv[1],"info")&&strcmp(argv[1],"check")){fprintf(stderr,"unknown command\n");return 64;}collect(&i);output(&i);return !strcmp(argv[1],"check")&&!compatible(&i,(char[96]){0},96)?2:0;}
