const app=document.querySelector('#app'),tabs=document.querySelector('#tabs');
const esc=v=>String(v??'Unknown').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url={system:'/system-information',installed:'/installed-applets',applets:'/api/applets',settings:'/webserver-settings',stations:'/standalone-radio/stations'};
async function load(u,o){const r=await fetch(u,o),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed ('+r.status+')');return j}
const token=()=>{let t=sessionStorage.getItem('sb-token');if(!t){t=prompt('Enter the management token shown in sbwebserver.log:')||'';if(t)sessionStorage.setItem('sb-token',t)}return t};
async function write(u,o={}){o.headers=Object.assign({'X-Management-Token':token()},o.headers||{});return load(u,o)}
function size(b){if(b==null)return'Unknown';const u=['B','KB','MB','GB'];let i=0,n=Number(b);while(n>=1024&&i<3){n/=1024;i++}return n.toFixed(i>1?1:0)+' '+u[i]}
function duration(v){let s=Math.floor(Number(v)||0),d=Math.floor(s/86400);s%=86400;return(d?d+' days ':'')+Math.floor(s/3600)+'h '+Math.floor(s%3600/60)+'m'}
function facts(a){return'<dl class="facts">'+a.map(x=>'<dt>'+esc(x[0])+'</dt><dd>'+esc(x[1])+'</dd>').join('')+'</dl>'}
function card(t,b){return'<section class="card"><h3>'+esc(t)+'</h3>'+b+'</section>'}
function disk(t,d){if(!d)return card(t,'<p>Not available</p>');return card(t,'<div class="big-number">'+esc(size(d.free_bytes))+' free</div><div class="meter"><span style="width:'+Number(d.used_percent||0)+'%"></span></div>'+facts([['Used',size(d.used_bytes)+' ('+d.used_percent+'%)'],['Total',size(d.total_bytes)],['Mount point',d.path]]))}
async function overview(){const [s,a]=await Promise.all([load(url.system),load(url.installed)]),active=s.network.interfaces.find(x=>x.up&&x.name!=='lo')||s.network.interfaces[0]||{};app.innerHTML='<section class="hero"><div><h2>'+esc(s.device.product)+'</h2><div class="address">'+esc(active.ip_address||s.device.hostname)+'</div></div><div class="status">SBWebserver online</div></section><div class="grid">'+card('Device',facts([['Hostname',s.device.hostname],['Kernel',s.operating_system.kernel],['Architecture',s.cpu.architecture],['Uptime',duration(s.operating_system.uptime_seconds)]]))+card('Network',facts([['Interface',active.name],['IP address',active.ip_address],['Gateway',s.network.gateway],['DNS',s.network.dns]]))+disk('Persistent storage',s.storage.persistent)+card('Installed applets',a.map(x=>'<div class="interface"><strong>'+esc(x.name)+'</strong> <span class="badge '+(x.installed?'':'off')+'">'+(x.installed?'Installed':'Not installed')+'</span></div>').join(''))+'</div>'}
async function system(){const s=await load(url.system),m=s.memory;app.innerHTML='<h2>System Information</h2><div class="grid">'+card('Device',facts([['Product',s.device.product],['Hostname',s.device.hostname],['Firmware',s.device.firmware],['Kernel',s.operating_system.kernel]]))+card('Memory',facts([['Total',size(m.total_kb*1024)],['Free',size(m.free_kb*1024)]]))+disk('Persistent storage',s.storage.persistent)+'</div>'}
async function settings(){const s=await load(url.settings);app.innerHTML='<h2>Settings</h2><section class="card"><form id="settings-form"><div class="form-row"><label>Display name</label><input id="name" value="'+esc(s.name)+'"></div><div class="form-row"><label><input id="readonly" type="checkbox" '+(s.readonly?'checked':'')+'> Read-only mode</label></div><button>Save</button><div id="message"></div></form></section>';document.querySelector('#settings-form').onsubmit=async e=>{e.preventDefault();try{await write(url.settings,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({port:80,readonly:document.querySelector('#readonly').checked,name:document.querySelector('#name').value})});document.querySelector('#message').textContent='Settings saved.'}catch(x){document.querySelector('#message').textContent=x.message}}}
const defs=[['name','Internal name'],['title','Title'],['version','Version'],['target','Target'],['min_target_version','Minimum target version'],['desc','Description'],['changes','Changes'],['creator','Creator'],['email','Email']];
function fields(x={}){return defs.map(([k,l])=>'<div class="form-row"><label>'+l+'</label><input name="'+k+'" maxlength="'+(k==='desc'||k==='changes'?512:128)+'" '+(k==='name'?'pattern="[A-Za-z][A-Za-z0-9_-]*" title="Letters, digits, underscore and hyphen only; no spaces"':'')+' value="'+esc(x[k]??(k==='target'?'baby':k==='min_target_version'?'7.7':''))+'"></div>').join('')}
function values(f){return Object.fromEntries([...f.querySelectorAll('[name]')].filter(x=>x.name!=='package').map(x=>[x.name,x.value.trim()]))}
async function applets(){const d=await load(url.applets);app.innerHTML='<h2>Applet Repository</h2><p>Uploading makes a package available to the Logitech Applet Installer; it does not install it.</p>'+(!d.storage_active?'<div class="notice error">Extended storage is not active. Local ZIP uploads are disabled.</div>':'')+'<section class="card"><h3>Catalog</h3><div class="table-wrap"><table><thead><tr><th>Title</th><th>Name</th><th>Version</th><th>Target</th><th>Source</th><th>SHA-1</th><th>Actions</th></tr></thead><tbody>'+d.applets.map((x,i)=>'<tr><td>'+esc(x.title)+'</td><td>'+esc(x.name)+'</td><td>'+esc(x.version)+'</td><td>'+esc(x.target)+'</td><td><span class="badge '+(x.source==='local'?'':'off')+'">'+esc(x.source)+'</span></td><td><code class="digest">'+esc(x.sha)+'</code></td><td><button data-edit="'+i+'">Edit</button> <button class="danger" data-remove="'+i+'">Remove</button>'+(x.source==='local'?' <a class="button" href="'+esc(x.url)+'">ZIP</a>':'')+'</td></tr>').join('')+'</tbody></table></div></section><section class="card"><h3>Upload applet ZIP</h3><form id="upload-form"><div class="form-row"><label>ZIP package</label><input name="package" type="file" accept=".zip" required></div>'+fields()+'<button '+(d.storage_active?'':'disabled')+'>Validate and add</button><progress id="progress" max="100" hidden></progress><div id="message"></div></form></section>';
 const f=document.querySelector('#upload-form'),msg=document.querySelector('#message'),p=document.querySelector('#progress');f.package.onchange=()=>{const m=f.package.files[0]?.name.match(/^([A-Za-z][A-Za-z0-9_-]*)-([A-Za-z0-9._+-]+)\.zip$/i);if(m){if(!f.elements.name.value)f.elements.name.value=m[1];if(!f.elements.version.value)f.elements.version.value=m[2]}};f.onsubmit=e=>{e.preventDefault();const file=f.package.files[0];if(!file)return;const fd=new FormData;fd.append('package',file,file.name);const xhr=new XMLHttpRequest;xhr.open('POST',url.applets+'/upload?'+new URLSearchParams(values(f)));xhr.setRequestHeader('X-Management-Token',token());p.hidden=false;xhr.upload.onprogress=e=>{if(e.lengthComputable)p.value=e.loaded*100/e.total};xhr.onload=()=>{let j={};try{j=JSON.parse(xhr.responseText)}catch(e){}if(xhr.status>=200&&xhr.status<300)applets();else{msg.className='notice error';msg.textContent=j.error||'Upload failed'}};xhr.onerror=()=>{msg.className='notice error';msg.textContent='Upload connection failed'};xhr.send(fd)};
 app.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editApplet(d.applets[+b.dataset.edit]));app.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{const x=d.applets[+b.dataset.remove];if(confirm('Remove '+x.title+' from the catalog? This does not uninstall it.')){await write('/api/applets/'+encodeURIComponent(x.name)+'?delete_package='+(x.source==='local'?1:0),{method:'DELETE'});applets()}})}
async function editApplet(x){app.innerHTML='<h2>Edit '+esc(x.title)+'</h2><section class="card"><form id="edit-form">'+fields(x)+(x.source==='external'?'<div class="form-row"><label>External URL</label><input name="url" value="'+esc(x.url)+'"></div><div class="form-row"><label>SHA-1</label><input name="sha" value="'+esc(x.sha)+'"></div>':'<input type="hidden" name="url" value="'+esc(x.url)+'"><input type="hidden" name="sha" value="'+esc(x.sha)+'">')+'<button>Save metadata</button> <button type="button" id="cancel">Cancel</button><div id="message"></div></form></section>';const f=document.querySelector('#edit-form');f.elements.name.readOnly=true;document.querySelector('#cancel').onclick=applets;f.onsubmit=async e=>{e.preventDefault();try{await write('/api/applets/'+encodeURIComponent(x.name),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(values(f))});applets()}catch(y){document.querySelector('#message').textContent=y.message}}}
async function stations(){const a=await load(url.stations);app.innerHTML='<h2>Standalone Radio</h2>'+card('Stations',a.map(x=>'<div class="interface"><strong>'+esc(x.name)+'</strong><code>'+esc(x.stream_url)+'</code></div>').join(''))}
async function show(p){tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));app.innerHTML='<div class="loading">Loading...</div>';try{await({overview,system,settings,stations,applets}[p]||overview)()}catch(e){app.innerHTML='<div class="notice error">Could not load this page: '+esc(e.message)+'</div>'}}
async function init(){try{const a=await load(url.installed);if(a.some(x=>x.id==='standalone-radio'&&x.installed&&x.supported))tabs.insertAdjacentHTML('beforeend','<button data-page="stations">Standalone Radio</button>')}catch(e){}tabs.onclick=e=>{const b=e.target.closest('button');if(b)show(b.dataset.page)};show('overview')}
init();
