const app=document.querySelector('#app'),tabs=document.querySelector('#tabs');
const esc=v=>String(v??'Unknown').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url={system:'/system-information',applets:'/installed-applets',settings:'/webserver-settings',stations:'/standalone-radio/stations'};
async function load(u,o){const r=await fetch(u,o);if(!r.ok)throw new Error('Request failed ('+r.status+')');return r.json()}
function size(b){if(b==null)return'Unknown';const u=['B','KB','MB','GB'];let i=0,n=Number(b);while(n>=1024&&i<3){n/=1024;i++}return n.toFixed(i>1?1:0)+' '+u[i]}
function duration(v){let s=Math.floor(Number(v)||0),d=Math.floor(s/86400);s%=86400;return(d?d+' days ':'')+Math.floor(s/3600)+'h '+Math.floor(s%3600/60)+'m'}
function facts(a){return'<dl class="facts">'+a.map(x=>'<dt>'+esc(x[0])+'</dt><dd>'+esc(x[1])+'</dd>').join('')+'</dl>'}
function card(t,b){return'<section class="card"><h3>'+esc(t)+'</h3>'+b+'</section>'}
function disk(t,d){if(!d)return card(t,'<p>Not available</p>');return card(t,'<div class="big-number">'+esc(size(d.free_bytes))+' free</div><div class="meter"><span style="width:'+Number(d.used_percent||0)+'%"></span></div>'+facts([['Used',size(d.used_bytes)+' ('+d.used_percent+'%)'],['Total',size(d.total_bytes)],['Mount point',d.path]]))}
async function overview(){const r=await Promise.all([load(url.system),load(url.applets)]),s=r[0],a=r[1],active=s.network.interfaces.find(x=>x.up&&x.name!=='lo')||s.network.interfaces[0]||{};app.innerHTML='<section class="hero"><div><h2>'+esc(s.device.product)+'</h2><div class="address">'+esc(active.ip_address||s.device.hostname)+'</div></div><div class="status">SBWebserver online</div></section><div class="grid">'+card('Device',facts([['Hostname',s.device.hostname],['Kernel',s.operating_system.kernel],['Architecture',s.cpu.architecture],['Uptime',duration(s.operating_system.uptime_seconds)]]))+card('Network',facts([['Interface',active.name],['IP address',active.ip_address],['Gateway',s.network.gateway],['DNS',s.network.dns]]))+disk('Persistent storage',s.storage.persistent)+card('Installed applets',a.map(x=>'<div class="interface"><strong>'+esc(x.name)+'</strong> <span class="badge '+(x.installed?'':'off')+'">'+(x.installed?'Installed':'Not installed')+'</span></div>').join(''))+'</div>'}
async function system(){const s=await load(url.system),m=s.memory,used=Math.max(0,m.total_kb-(m.available_kb||m.free_kb)),interfaces=s.network.interfaces.map(i=>'<div class="interface"><strong>'+esc(i.name)+'</strong> <span class="badge '+(i.up?'':'off')+'">'+(i.up?'Up':'Down')+'</span><code>'+esc(i.ip_address)+' · '+esc(i.netmask)+' · '+esc(i.mac_address)+'</code></div>').join('');app.innerHTML='<h2>System Information</h2><p>Live diagnostic information reported by the Radio.</p><div class="grid">'+card('Device',facts([['Product',s.device.product],['Hostname',s.device.hostname],['Hardware',s.device.hardware],['Hardware revision',s.device.hardware_revision],['Serial number',s.device.serial_number],['Firmware',s.device.firmware],['Firmware build',s.device.firmware_build]]))+card('Operating system',facts([['System',s.operating_system.system],['Kernel',s.operating_system.kernel],['Machine',s.operating_system.machine],['Uptime',duration(s.operating_system.uptime_seconds)],['Local time',s.operating_system.current_time],['Timezone',s.operating_system.timezone],['Load averages',s.operating_system.load_average]]))+card('Processor',facts([['Model',s.cpu.model],['Architecture',s.cpu.architecture],['BogoMIPS',s.cpu.bogomips],['Features',s.cpu.features]]))+card('Memory','<div class="big-number">'+size((m.total_kb-used)*1024)+' available</div><div class="meter"><span style="width:'+(m.total_kb?Math.round(used*100/m.total_kb):0)+'%"></span></div>'+facts([['Total RAM',size(m.total_kb*1024)],['Free RAM',size(m.free_kb*1024)],['Buffers',size(m.buffers_kb*1024)],['Cached',size(m.cached_kb*1024)],['Swap',size(m.swap_free_kb*1024)+' free of '+size(m.swap_total_kb*1024)]]))+disk('Root filesystem',s.storage.root)+disk('Persistent storage',s.storage.persistent)+card('Network',facts([['Default gateway',s.network.gateway],['DNS server',s.network.dns]])+interfaces)+card('Services',facts([['SqueezePlay',s.services.squeezeplay?'Running':'Stopped'],['SBWebserver','Running'],['HTTPS Proxy',s.services.https_proxy?'Running':'Stopped'],['Standalone Radio',s.services.standalone_radio_installed?'Installed':'Not installed']]))+card('SBWebserver',facts([['Version',s.software.sbwebserver_version],['Mongoose',s.software.mongoose_version],['Built',s.software.build_date],['Applet path',s.software.applet_path],['Configuration',s.software.config_path]]))+'</div>'}
async function settings(){const s=await load(url.settings);app.innerHTML='<h2>Settings</h2><section class="card"><h3>SBWebserver settings</h3><form id="settings-form"><div class="form-row"><label for="name">Display name</label><input id="name" maxlength="63" value="'+esc(s.name)+'"></div><div class="form-row"><label for="port">HTTP port</label><input id="port" value="80" disabled></div><div class="form-row"><label><input id="readonly" type="checkbox" '+(s.readonly?'checked':'')+'> Read-only mode</label></div><button type="submit">Save settings</button><div id="message"></div></form></section>';document.querySelector('#settings-form').onsubmit=async e=>{e.preventDefault();const body={port:80,enabled:true,autostart:true,readonly:document.querySelector('#readonly').checked,name:document.querySelector('#name').value},msg=document.querySelector('#message');try{await load(url.settings,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});msg.className='notice';msg.textContent='Settings saved.'}catch(err){msg.className='notice error';msg.textContent=err.message}}}
async function stations(){const a=await load(url.stations);app.innerHTML='<h2>Standalone Radio</h2><section class="card"><div class="toolbar"><a class="button" href="/standalone-radio/stations.csv">Download CSV</a></div>'+(a.length?'<table><thead><tr><th>Name</th><th>Stream URL</th><th>Logo URL</th></tr></thead><tbody>'+a.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.stream_url)+'</td><td>'+esc(x.logo_url)+'</td></tr>').join('')+'</tbody></table>':'<div class="station-empty">No custom stations configured.</div>')+'</section>'}
async function show(p){tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));app.innerHTML='<div class="loading">Loading…</div>';try{await({overview,system,settings,stations}[p]||overview)()}catch(e){app.innerHTML='<div class="notice error">Could not load this page: '+esc(e.message)+'</div>'}}
async function init(){try{const a=await load(url.applets);if(a.some(x=>x.id==='standalone-radio'&&x.installed&&x.supported))tabs.insertAdjacentHTML('beforeend','<button data-page="stations">Standalone Radio</button>')}catch(e){}tabs.onclick=e=>{const b=e.target.closest('button');if(b)show(b.dataset.page)};show('overview')}
init();
