#include "system_info.h"
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <time.h>
#include <unistd.h>
#include <sys/utsname.h>
#include <sys/statvfs.h>
#include <sys/types.h>
#include <dirent.h>
#include <ifaddrs.h>
#include <arpa/inet.h>
#include <net/if.h>

typedef struct { char *p; size_t left; } Writer;
static void add(Writer*w,const char*fmt,...){if(w->left<2)return;va_list ap;va_start(ap,fmt);int r=vsnprintf(w->p,w->left,fmt,ap);va_end(ap);if(r<0)return;size_t n=(size_t)r;if(n>=w->left){w->p+=w->left-1;w->left=1;}else{w->p+=n;w->left-=n;}}
static void esc(Writer*w,const char*s){add(w,"\"");for(;s&&*s;s++){unsigned char c=(unsigned char)*s;if(c=='"'||c=='\\')add(w,"\\%c",c);else if(c>=32)add(w,"%c",c);}add(w,"\"");}
static void first(const char*path,char*out,size_t n){FILE*f=fopen(path,"r");if(!f){snprintf(out,n,"Unknown");return;}if(!fgets(out,n,f))snprintf(out,n,"Unknown");out[strcspn(out,"\r\n")]=0;fclose(f);}
static void value(const char*path,const char*key,char*out,size_t n){FILE*f=fopen(path,"r");char line[256];out[0]=0;if(!f)return;while(fgets(line,sizeof line,f)){char*p=strchr(line,':'),*end;if(!p)continue;*p++=0;end=line+strlen(line);while(end>line&&(end[-1]==' '||end[-1]=='\t'))*--end=0;if(!strcmp(line,key)){while(*p==' '||*p=='\t')p++;snprintf(out,n,"%s",p);out[strcspn(out,"\r\n")]=0;break;}}fclose(f);}
static long mem_kb(const char*key){FILE*f=fopen("/proc/meminfo","r");char k[64];long v=0;if(!f)return 0;while(fscanf(f,"%63s %ld%*[^\n]\n",k,&v)==2){k[strcspn(k,":")]=0;if(!strcmp(k,key)){fclose(f);return v;}}fclose(f);return 0;}
static void disk(Writer*w,const char*path){struct statvfs s;if(statvfs(path,&s)){add(w,"null");return;}unsigned long long total=(unsigned long long)s.f_blocks*s.f_frsize,freeb=(unsigned long long)s.f_bavail*s.f_frsize;add(w,"{\"path\":");esc(w,path);add(w,",\"total_bytes\":%llu,\"used_bytes\":%llu,\"free_bytes\":%llu,\"used_percent\":%u}",total,total-freeb,freeb,total?(unsigned)((total-freeb)*100/total):0);}
static void gateway(char*out,size_t n){FILE*f=fopen("/proc/net/route","r");char iface[32];unsigned long dest,gw;out[0]=0;if(!f)return;char line[256];fgets(line,sizeof line,f);while(fgets(line,sizeof line,f)){if(sscanf(line,"%31s %lx %lx",iface,&dest,&gw)==3&&dest==0){snprintf(out,n,"%lu.%lu.%lu.%lu",gw&255,(gw>>8)&255,(gw>>16)&255,(gw>>24)&255);break;}}fclose(f);}
static void dns(char*out,size_t n){FILE*f=fopen("/etc/resolv.conf","r");char k[32],v[128];out[0]=0;if(!f)return;while(fscanf(f,"%31s %127s",k,v)==2)if(!strcmp(k,"nameserver")){snprintf(out,n,"%s",v);break;}fclose(f);}
static int proc_running(const char*needle){DIR*d=opendir("/proc");struct dirent*e;if(!d)return 0;while((e=readdir(d))){if(e->d_name[0]<'0'||e->d_name[0]>'9')continue;char p[96],v[128];snprintf(p,sizeof p,"/proc/%s/comm",e->d_name);first(p,v,sizeof v);if(strstr(v,needle)){closedir(d);return 1;}}closedir(d);return 0;}
void system_json(char*out,size_t n){Writer w={out,n};struct utsname u;char host[128]="Unknown",cpu[128]="Unknown",hardware[128]="Unknown",revision[64]="Unknown",serial[64]="Unknown",bogomips[64]="Unknown",features[256]="Unknown",firmware[128]="Unknown",build[128]="Unknown",uptime[64]="0",load[128]="Unknown",gw[64],resolver[128],now[64],zone[32];double up=0;time_t t=time(0);struct tm*tm=localtime(&t);uname(&u);gethostname(host,sizeof host);value("/proc/cpuinfo","Processor",cpu,sizeof cpu);value("/proc/cpuinfo","Hardware",hardware,sizeof hardware);value("/proc/cpuinfo","Revision",revision,sizeof revision);value("/proc/cpuinfo","Serial",serial,sizeof serial);value("/proc/cpuinfo","BogoMIPS",bogomips,sizeof bogomips);value("/proc/cpuinfo","Features",features,sizeof features);first("/etc/squeezeos.version",firmware,sizeof firmware);first("/etc/version",build,sizeof build);first("/proc/uptime",uptime,sizeof uptime);sscanf(uptime,"%lf",&up);first("/proc/loadavg",load,sizeof load);gateway(gw,sizeof gw);dns(resolver,sizeof resolver);if(tm){strftime(now,sizeof now,"%Y-%m-%d %H:%M:%S",tm);strftime(zone,sizeof zone,"%Z",tm);}else{snprintf(now,sizeof now,"Unknown");snprintf(zone,sizeof zone,"Unknown");}
add(&w,"{\"device\":{\"product\":\"Logitech Squeezebox Radio\",\"hostname\":");esc(&w,host);add(&w,",\"hardware\":");esc(&w,hardware);add(&w,",\"hardware_revision\":");esc(&w,revision);add(&w,",\"serial_number\":");esc(&w,serial);add(&w,",\"firmware\":");esc(&w,firmware);add(&w,",\"firmware_build\":");esc(&w,build);add(&w,"},\"operating_system\":{\"kernel\":");esc(&w,u.release);add(&w,",\"machine\":");esc(&w,u.machine);add(&w,",\"system\":");esc(&w,u.sysname);add(&w,",\"uptime_seconds\":%.0f,\"current_time\":",up);esc(&w,now);add(&w,",\"timezone\":");esc(&w,zone);add(&w,",\"load_average\":");esc(&w,load);
add(&w,"},\"cpu\":{\"model\":");esc(&w,cpu);add(&w,",\"architecture\":");esc(&w,u.machine);add(&w,",\"bogomips\":");esc(&w,bogomips);add(&w,",\"features\":");esc(&w,features);add(&w,"},\"memory\":{\"total_kb\":%ld,\"free_kb\":%ld,\"available_kb\":%ld,\"buffers_kb\":%ld,\"cached_kb\":%ld,\"swap_total_kb\":%ld,\"swap_free_kb\":%ld}",mem_kb("MemTotal"),mem_kb("MemFree"),mem_kb("MemAvailable"),mem_kb("Buffers"),mem_kb("Cached"),mem_kb("SwapTotal"),mem_kb("SwapFree"));
add(&w,",\"storage\":{\"root\":");disk(&w,"/");add(&w,",\"persistent\":");disk(&w,"/mnt/storage");add(&w,"},\"network\":{\"gateway\":");esc(&w,gw[0]?gw:"Unknown");add(&w,",\"dns\":");esc(&w,resolver[0]?resolver:"Unknown");add(&w,",\"interfaces\":[");struct ifaddrs*ifs=0,*it;int comma=0;if(getifaddrs(&ifs)==0){for(it=ifs;it;it=it->ifa_next){if(!it->ifa_addr||it->ifa_addr->sa_family!=AF_INET)continue;char ip[INET_ADDRSTRLEN],mask[INET_ADDRSTRLEN],mac[64]="Unknown",mp[128];inet_ntop(AF_INET,&((struct sockaddr_in*)it->ifa_addr)->sin_addr,ip,sizeof ip);inet_ntop(AF_INET,&((struct sockaddr_in*)it->ifa_netmask)->sin_addr,mask,sizeof mask);snprintf(mp,sizeof mp,"/sys/class/net/%s/address",it->ifa_name);first(mp,mac,sizeof mac);add(&w,"%s{\"name\":",comma++?",":"");esc(&w,it->ifa_name);add(&w,",\"ip_address\":");esc(&w,ip);add(&w,",\"netmask\":");esc(&w,mask);add(&w,",\"mac_address\":");esc(&w,mac);add(&w,",\"up\":%s}",(it->ifa_flags&IFF_UP)?"true":"false");}freeifaddrs(ifs);}add(&w,"]}");
add(&w,",\"services\":{\"squeezeplay\":%s,\"sbwebserver\":true,\"https_proxy\":%s,\"standalone_radio_installed\":%s},\"software\":{\"sbwebserver_version\":\"0.1.0\",\"mongoose_version\":\"7.17\",\"build_date\":\"%s %s\",\"applet_path\":\"/usr/share/jive/applets/SBWebserver\",\"config_path\":\"/mnt/storage/sbwebserver\"}}",(proc_running("squeezeplay")||proc_running("jive"))?"true":"false",proc_running("sbproxy")?"true":"false",access("/usr/share/jive/applets/StandaloneRadio",F_OK)==0?"true":"false",__DATE__,__TIME__);}
